apiVersion: v1
kind: Pod
metadata:
  name: docker-registry
  namespace: kube-system
  labels:
    k8s-app: docker-registry
spec:
  containers:
  - name: docker-registry
    image: registry:2
    ports:
    - containerPort: 5000
  - name: registry-proxy
    image: nginx
    ports:
    - containerPort: 443
      hostPort: 5000
    volumeMounts:
    - mountPath: /etc/nginx
      name: nginx-conf
      readOnly: true
  volumes:
  - name: nginx-conf
    hostPath:
      path: /etc/registry

---

apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: kube-system
spec:
  selector:
    k8s-app: docker-registry
  clusterIP: 10.20.0.100
  ports:
  - name: https
    protocol: TCP
    port: 5000
